function [X,Y] = edges2stairs(edges,counts)
% Convert edges and counts (generated by histcounts) into coordinates for a
% stair-plot
%
% This function is usefull for plotting histogram data in unconventional
% ways (e.g. with axes swapped).

X = reshape([reshape(edges,1,[]);reshape(edges,1,[])],[],1);
Y = reshape([reshape(counts,1,[]);reshape(counts,1,[])],[],1);
Y = [0;Y;0];