classdef RoiTracker < extras.Async.ParameterProcessor 
% Asynchronous Radialcenter image processor
% RoiTracker can be passed images or ImageStruct having the fields
%   ImageStruct.ImageData: numeric array holding image
%   ImageStruct.Time: scalar double indicating timestamp of image in MATLAB
%                     datenum format
%
% RoiTracker uses Parameters (see setParameter) to determine tracking
% regions.
%   You should pass a struct array roiList specifying which regions in an
%   image should be tracked. See extras.roi.roiObject for details
%       strut array should be generated by calling
%           obj.setParameters('roiList',toStruct(YourRoiArray));
%
% Processor Generates Results Data which is a Struct holding the fields:
%   ResultData. ...
%           ...
%           .ImageStruct: (optional, if IncludeImageInResult=true) struct
%                         containing ImageData.
%           .Time: datenum timestamp coresponding to ImageStruct.Time or
%                  the time when the result was processed (if IS.Time not
%                  specified).
%           .roiList(n): struct array with roi info
%               .Window
%               ...
%               .CentroidResult: struct holding centroid fit data
%                   .xyMethod: string listing centroid algorithm
%                   .X
%                   .Y
%                   .varXY
%                   .RWR_N
%
% Dependencies:
%   Relies on extras.ParticleTracking.RoiTracker.RoiTracker_mex
%   See ...\+extras\+ParticleTracking\+RoiTracker\source for c++ code
%% Copyright 2019, Daniel T. Kovari, Emory University
%  All rights reserved.

    %% Create
    methods
        function this = RoiTracker()
            this@extras.Async.ParameterProcessor(@extras.ParticleTracking.RoiTracker.RoiTracker_mex)
            this.Name = 'RoiTracker'; %Change Name
            this.ResultsCheckTimerPeriod = 1/20;
            this.ErrorCheckTimerPeriod = 1/20;
        end
    end

    %% IncludeImage
    properties(Dependent)
        IncludeImageInResult (1,1) logical; %T/F indicating if images should be included in the results struct
    end
    methods
        function tf = get.IncludeImageInResult(this)
            tf = this.runMethod('IncludeImageData');
        end
        function set.IncludeImageInResult(this,val)
            this.runMethod('IncludeImageData',val);
        end
    end

end
