classdef AsyncProcessorError < event.EventData
% Error Event generated by AsyncProcessor when a task in the queue thros an error
%% Copyright 2019 Daniel T. Kovari, Emory University
%   All rights reserved.

    properties
        identifier
        message
        mex_function_name
    end
    
    %% constructor
    methods
        function this = AsyncProcessorError(errMsg,mex_function_name)
        %construct error event from Error message struct
        % Inputs
        %   errMsg: Error message struct returned by MEX AsyncProcessor
        %   mex_function_name: string specifying name of the MEX function
        %                      which generated the error.
        
            this.identifier = errMsg.identifier;
            this.message = errMsg.message;
            this.mex_function_name = mex_function_name;
        end
    end
    
    %% other methods
    methods
        function printReport(this)
            for n=1:numel(this)
                fprintf('\n==================================================================\n');
                fprintf('AsyncProcessorError: %s\n',this(n).identifier);
                fprintf('- Source: %s\n',class(this(n).Source));
                fprintf('- Mex Function: %s\n',this(n).mex_function_name);
                fprintf('- Message --------------------------------------------------------\n')
                fprintf('%s\n',this(n).message);
                fprintf('==================================================================\n')
            end
        end
    end
    

end
